# Домашнее задание по лекции "Библиотека numpy. Вычислительные задачи."

## Задание 1
Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).

In [10]:
import numpy as np

N = 12
np.arange(N-1, -1, -1)

array([11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

## Задание 2
Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.

In [62]:
N = 12
diag_array_n = np.diag(np.arange(N-1, -1, -1), k=0)
sum_diag = diag_array_n.sum()

print(f'Диагональная матрица: \n{diag_array_n}')
print(f'Сумма значений диагонали равна {sum_diag}')

Диагональная матрица: 
[[11  0  0  0  0  0  0  0  0  0  0  0]
 [ 0 10  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  9  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  8  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  7  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  6  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  5  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  4  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  3  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  2  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  1  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0]]
Сумма значений диагонали равна 66


## Задание 3
Решите систему уравнений:

4x + 2y + z = 4

x + 3y = 12

5y + 4z = -3

In [63]:
# матрицы левой (а) и правой (b) частей:
a = np.array([[4, 2, 1], [1, 3, 0], [0, 5, 4]])
b = np.array([4, 12, -3])
# решиние системы уравнений:
from numpy import linalg
linalg.solve(a, b)

array([ 0.46666667,  3.84444444, -5.55555556])

In [64]:
print(a, b)
# проверка верности
np.allclose( np.dot(a, linalg.solve(a, b)), b )

[[4 2 1]
 [1 3 0]
 [0 5 4]] [ 4 12 -3]


True

## Задача 4 домашнего задания
Имеется матрица покупок в интернет-магазине. Столбец А - ID пользователя. Остальные столбцы - количество покупок категорий товаров этим пользователем:

In [22]:
users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], 
    np.int32
)

На сайт заходит очередной посетитель, о покупках которого известно следующее:

In [23]:
next_user_stats = np.array([0, 1, 2, 0, 0, 0])

Найдите самого похожего пользователя. Т. е. посчитайте косинусное расстояние между этим пользователем и всеми пользователями из массива user_stats

**Решение:**

In [30]:
def cosine( a, b ):
    """
    Подсчет косинуса угла между векторами a, b по их координатам
    """
    
    # длины векторов
    aLength = np.linalg.norm( a )
    bLength = np.linalg.norm( b )
    
    return np.dot( a, b ) / ( aLength * bLength )

In [65]:
user_cos = {}
for id, user in enumerate(users_stats):
    user_cos[id] = cosine( user, next_user_stats ) # вычисление косинусного расстояния
    
# user_id c максимальныv косинусом:
nearest_user = [x for x, cos_x in user_cos.items() if cos_x == max(user_cos.values())][0] 

# print(nearest_user)
# max(user_cos.values())
# print(user_cos)
print(f'Очередной посетитель {next_user_stats}',
      f'наиболее близок ({round(max(user_cos.values()), 3)}) к посетителю №{nearest_user} {users_stats[nearest_user]}')

Очередной посетитель [0 1 2 0 0 0] наиболее близок (0.949) к посетителю №7 [0 1 1 0 0 0]
